#!/usr/bin/env ruby

require 'yaml'
['lib/notification', 'lib/email', 'lib/sms', 'lib/host', 'lib/host_monitor'].each do |dep|
  require File.expand_path(dep)
end

if File.exists?('config.yml')
  $config = File.open('config.yml') { |config| YAML.load(config) }

  host = Host.new($config['host']['url'], $config['host']['timeout'])
  monitor = HostMonitor.new(host)
  monitor.start
else
  puts 'Please, configure application: add some settings to config.yml'
end
